### PR TITLE
Update Physics.hx

### PR DESCRIPTION
**Pull request by OscarLeif**
Setup the Physics listener.
This case I really try to avoid the Dynamic for the data table that returns, but each event:Hash message the data table change.

But for now this works. The thing is for each event like 

```haxe
function onPhysicsContact(event:Hash, data:Dynamic):Void 
{
	if (event == hash("trigger_event")) 
        {
          trace(data.enter); // true or false
          trace(data.a.id); // [/go2]
          trace(data.a.group); // [default],
          trace(data.b.id); // this is the other player trigger sensor, this is sensor.
        }
}
```

well the data that return is here.
https://defold.com/ref/stable/physics/#physics.set_listener:callback

### CODE REVIEW

**Comment by haath** [comment]
I think `Dynamic` can easily be avoided here.

We can go the same way as [`Message<T>`](https://github.com/hxdefold/hxdefold/blob/master/src/defold/types/Message.hx).

You can take inspiration from how the [`onMessage`](https://github.com/hxdefold/hxdefold/blob/master/src/defold/support/Script.hx#L67) callback is generic over the message type, and do something similar for physics events.

The cool thing with this approach is that, just like in `onMessage`, a simple switch statement would be able to disambiguate the type of the event.

For example it could look like this:

```haxe
function myPhysicsListener<TEvent>(event: PhysicsEvent<TEvent>, data: TEvent)
{
    switch event
    {
        case ContactPointEvent:
            // here "data" is automatically of some ContactPointEvent typedef

        case CollisionEvent:
            // here "data" is automatically of some CollisionEvent typedef

        // etc...
    }
}
```

Here I'm also assuming that `PhysicsEvent<T>` would be an (abstract) enum, since that would be the most ergonomic in this situation where we have a finite number of cases.

**Comment by OscarLeif** [comment]
I will check again. There's not a lot of documentation.
I was thinking this because depending on each response we get a different msg.

**Comment by haath** [comment]
> I was thinking this because depending on each response we get a different msg.

It's the same with `onMessage` 🙂 

```haxe
override function onMessage<TMessage>(messageId:Message<TMessage>, message:TMessage, sender:Url)
{
    switch messageId
    {
        case CameraMessages.set_camera:
            // here the compiler knows that "message" is of type "CameraMessageSetCamera"!
            print(message.aspect_ratio);
            print(message.orthographic_zoom);
    }
}
```

This is indeed some Haxe magic that isn't well documented.

**Comment by OscarLeif** [comment]
Make a new pull request:

https://github.com/hxdefold/hxdefold/pull/44

**Pull request closed without merging**
